[package]
name = "sljs-cli"
version = "0.1.0"
authors = ["Dmytro S <me@dmytrish.net>"]
edition = "2021"
description = "A toy JavaScript runtime"

[dependencies]
atty = "0.2"
clap = {version = "3.2.16", features = ["derive"]}

[dependencies.slothjs]
path = ".."