title: language-incubator
description: "My sandbox for learning compilers, interpreters, code generation, virtual machines, assemblers, JITs, etc. "
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
